### ISSUE TITLE
Add username to complaint tracker landing page

### ISSUE THREAD

**Issue by Sgtpluck** [OHS-Hosting-Infrastructure/complaint-tracker#10]
As a PS,
I want to see that the tracker knows who I am
so I know I am in the right place

Acceptance Criteria:
* Navigate to $STAGING-URL
* Log in
You should be redirected to a landing page that says "Hi, $USERNAME" where $USERNAME is the name that you are using! 

Notes:
* Fallback to email address in case there is no first name/last name?

**Comment by jduss4** [comment]
Partly addressed in #38
