### ISSUE TITLE
unlink TTA activity report 

### ISSUE THREAD

**Issue by Sgtpluck** [OHS-Hosting-Infrastructure/complaint-tracker#140]
User Story:
As a program specialist
I want to unlink an existing activity report ID
So that I can easily fix a mistake

Acceptance:
Given that I am a program specialist
When I click on an AR ID and delete it
Then the detail disappears

Related to issue #96 

https://user-images.githubusercontent.com/85581840/132394891-48e902a5-f8fc-4447-a0b8-4e557d3933d8.png

Notes for @lauranash18f:
* how do we want delete to look?

**Comment by lauranash18f** [comment]
Full matrix in Figma, uploaded relevant designs here as well. https://www.figma.com/file/k8sPnWItmiBAyF4cw6Uuog/OHS-Complaints-Tracker?node-id=0%3A1

![Default](https://user-images.githubusercontent.com/85581840/134046136-4b91b110-4f27-4ae2-be6b-79b1c9ddbe92.png)
![Deletion Confirmation](https://user-images.githubusercontent.com/85581840/134046139-833d64b8-e1bd-4c7b-851a-d9d9b08d1a04.png)
![Deletion Confirmation (1)](https://user-images.githubusercontent.com/85581840/134046141-c0d85cc1-dd4d-4d77-8d1a-05c297362ff5.png)
