### ISSUE TITLE
Adding TTA activity report to complaint fails in fake data

### ISSUE THREAD

**Issue by jduss4** [OHS-Hosting-Infrastructure/complaint-tracker#179]
**Describe the bug**

When adding an activity report to an issue, the rails app throws an error

**To Reproduce**

1. Start app in development mode (fake data)
1. Navigate to issue detail page
1. Click "Add TTA Activity Report" and enter a number
1. Get error in hses_access_token.rb

```
NoMethodError in IssueTtaReportsController#create
undefined method `with_indifferent_access' for nil:NilClass

@credentials = creds.dup.with_indifferent_access
```

**Expected behavior**

Expected to see activity report associated with issue in UI OR get a permission denied type warning

**Screenshots**

What I get on development
![image](https://user-images.githubusercontent.com/2480492/137344694-262c24c8-e605-494a-9aa7-3af1a54163a6.png)

What I see on production (this is acceptable behavior)
![image](https://user-images.githubusercontent.com/2480492/137344756-657d4209-4021-4835-a761-fd658b1c0b3d.png)

**Comment by jduss4** [comment]
After messing around a little bit, this appears to only be happening when I am logged into HSES with the test user and just using `rails s` to start the server. However, using `CT_BYPASS_AUTH=true` means I can add activity reports like normal.

**Comment by rahearn** [comment]
This should be working, though this makes sense if you were already logged in when the access token code was added. If you see it again can you try to log out and log in?

**Comment by jduss4** [comment]
I haven't seen it again, although it may still be an issue, but I'm happy to close this for now.
