### ISSUE TITLE
Brainstorm initial data we want from HSES

### ISSUE THREAD

**Issue by jduss4** [OHS-Hosting-Infrastructure/complaint-tracker#20]
User story:
As an engineer
I want to come up with a list of fields we would like returned from a future HSES API endpoint
So that we can prepare our first ask of their developers to build this endpoint

Acceptance:
- [x] we have gone through the schema to identify fields of interest
- [x] we have compiled relevant ones into a list
- [x] we have checked with @lauranash18f to make sure we're lining up with the type of data she has identified through workflow

**Comment by jduss4** [comment]
Not sure how sensitive the fields are, so not posting them here.  They are available in a [google doc](https://docs.google.com/document/d/1j0ICytviL0QXM5sYBCeAH0-6Nhj0Y5OyiSz6H7VZHx0/edit#heading=h.uier5yjij09y), instead.

**Comment by lauranash18f** [comment]
I can't check the box due to permissions, so giving @jduss4 permission to do so on my behalf in the meantime.
