### ISSUE TITLE
Date Created label - S

### ISSUE THREAD

**Issue by matt-dobson** [OHS-Hosting-Infrastructure/complaint-tracker#25]
User Story:
As a Program Specialist
I want to see the date when a complaint was entered into HSES
So that I know when it was entered and how long it takes to close

Acceptance:
Given that I am a Program Specialist 
When I look at the complaints list
Then I can see when it was entered into HSES in a"date created" column

**Comment by matt-dobson** [comment]
I'm thinking every action and update should have date and time associated. Do we nee a story for each?

**Comment by matt-dobson** [comment]
There is a creationDate with timestamp for HSES entry:

        "createdByCustomerService": false,
        "creationDate": "06/01/2020, 17:07:46.094",

**Comment by jduss4** [comment]
Changing label from Date -> Date Created to minimize confusion about what the date column of the table represents.
