### ISSUE TITLE
TTA Referral label

### ISSUE THREAD

**Issue by matt-dobson** [OHS-Hosting-Infrastructure/complaint-tracker#31]
User Story:
As a Program Specialist
I want to flag that I've referred TTA in response to a complaint
So that I can keep track of how the complaint is being addressed

Acceptance:
Given that I am a Program Specialist
When I label a complaint "TTA Referral"
Then I see a label that says "TTA Referral"

**Comment by lauranash18f** [comment]
Changed Deployed to Referral, since that is the language used internally.

**Comment by lauranash18f** [comment]
Closing as duplicate.
