### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by matt-dobson** [OHS-Hosting-Infrastructure/complaint-tracker#51]
User Story:
As a Program Specialist
I want to Log Out from the Complaints Tracker
So that no one can access the Complaints Tracker from my computer

Acceptance:
Given that I am a Program Specialist
When I press the log out button
Then I will be logged out and see a message that confirms the log out and a button to log back in.

**Comment by lauranash18f** [comment]
Design added to Figma: https://www.figma.com/file/k8sPnWItmiBAyF4cw6Uuog/OHS-Complaints-Tracker?node-id=0%3A1

**Comment by jduss4** [comment]
@lauranash18f 's design:
![image](https://user-images.githubusercontent.com/2480492/129624063-831d8924-47e6-491a-bea1-a90da0e6e14c.png)
