### ISSUE TITLE
Investigate error checking of pa11y script

### ISSUE THREAD

**Issue by rahearn** [OHS-Hosting-Infrastructure/complaint-tracker#55]
**Describe the bug**
It looks like the pa11y action is passing even when the scan fails, at least in the case where something is wrong with pa11y itself.

**To Reproduce**
1. See https://github.com/OHS-Hosting-Infrastructure/complaint-tracker/pull/54#issuecomment-897753130

**Expected behavior**

The action fails when pa11y either finds an accessibility issue or does not successfully run

**Comment by jduss4** [comment]
I would be interested in pairing with somebody on this one, if anybody is looking to tackle it soon :)
