### ISSUE TITLE
Select license

### ISSUE THREAD

**Issue by jduss4** [OHS-Hosting-Infrastructure/complaint-tracker#67]
User Story:
As a stakeholder
I want to have a license explaining the terms of reuse, modification, etc,
So that I understand and approve of how others can use this code.

Acceptance:
- ~ADR detailing several license options and the pros / cons to consider~ (turns out we don't have any options :) )
- [ ] A license has been added to this repository as a file

**Comment by rahearn** [comment]
We might not have much of an option for license, as a work of the US Government. Example from login.gov: https://github.com/18F/identity-idp/blob/main/LICENSE.md

**Comment by jduss4** [comment]
Well that makes things pretty simple

**Comment by jduss4** [comment]
Okay, I found some semi-formal guidance about this:  https://handbook.tts.gsa.gov/training-and-development/intro-to-github/#1-repository-basics

> The license on every repo must be Creative Commons 0, or CC0. That’s shorthand for Public Domain. TTS is not only committed to working in the public domain by our own policies, but is also committed by law. (Though we are allowed to by law, we don’t trademark our logo.) There are a few exceptions to that rule, so check with #admins-github and #wg-opensource before putting any license other than CC0 on your project.
