### ISSUE TITLE
Complaint Detail Summary Box - M

### ISSUE THREAD

**Issue by matt-dobson** [OHS-Hosting-Infrastructure/complaint-tracker#70]
User Story:
As a Program Specialist
I want to see be able to get a summary of the issue
So that I can get more information than I can see in the table

Acceptance:
Given that I am a Program Specialist
When I click on the issue number in the complaints list
Then I go to a detail page for that complaint and will see:

Grantee Name
Issue (short description field, not truncated like it is in the table)

**Comment by lauranash18f** [comment]
Design is ready in Figma and base state is attached (additional states for timeline added, assuming different story.).
![Complaint Detail Page: No Header Backing](https://user-images.githubusercontent.com/85581840/129911274-6054b366-14e7-40bd-824f-53dfa9f846e1.png)

This particular ticket covers the content in the header and summary card sections of the detail page. Timeline will need to be a new story (stories).

**Comment by matt-dobson** [comment]
Pull out lLink to view the full complaint in HSES as a separate story @matt-dobson
