### ISSUE TITLE
Complaint Status - S

### ISSUE THREAD

**Issue by matt-dobson** [OHS-Hosting-Infrastructure/complaint-tracker#71]
User Story:
As a Program Specialist
I want to sort my assigned complaints by status
So that I know the status of my complaints and can move the more timely ones to the top of my list

Acceptance:
Given that I am a Program Specialist
When I  click on the status column of my complaints list
Then I see the status of complaints listed in the status column as: 

"New"
"Rec. Reopening"
"Reopened"
"In Progress"
"Rec. Closure"
"Closed"

**Comment by matt-dobson** [comment]
Design: https://www.figma.com/file/k8sPnWItmiBAyF4cw6Uuog/OHS-Complaints-Tracker?node-id=0%3A1

**Comment by lauranash18f** [comment]
Status sort order:

- **New** (can skip for now, as we do not know if it will exist. But if this exists at all, it is first.)
- **Rec. Reopening** (reasons: this is generally an action taken by someone who is NOT the user so should be visible, generally requires immediate action to reopen it)
- **Reopened** (reasons it's above Open: generally for cases that have been open awhile, visibility, it's reopened so new work needs to be done — also to keep it near Rec. Reopening so things aren't jumping around as much... also this is rare)
- **Open**
- **Rec. Closure**
- **Closed**

To stave off scope creep on this one, this does NOT include::
- Pinning the yellow cases to the top of the chart (or beneath "new" if New ends up existing.)
- secondary sorts (what you do with ties... most likely this will be by date or inherit from previous sort but that is something to discuss and will be a separate ticket)
- figuring out the definition or existence of New

**Comment by Sgtpluck** [comment]
color follow-up has been moved to #81

**Comment by lauranash18f** [comment]
Looks great, removed the word "formatted" from the user story as well to avoid confusion in the future.
