### ISSUE TITLE
Dev login without auth

### ISSUE THREAD

**Issue by Sgtpluck** [OHS-Hosting-Infrastructure/complaint-tracker#8]
As a dev,
I want to be able to bypass log in
so that I don't have to connect to anything to get into the app

Acceptance Criteria:
* On a dev environment
* Navigate to $STAGING-URL
* There should be screen that directs you to log in via HSES with a button
* Hit the button
You should be redirected to a landing page that will eventually house the summary view of PS's complaints.
* In the staging environment
* Navigate to $STAGING-URL
* There should be screen that directs you to log in via HSES with a button
* Hit the button
Nothing should happen

**Comment by rahearn** [comment]
We do not need to do this until we're storing users locally. Moving to the Ideas/Icebox until that point
