### ISSUE TITLE
Terrific Terraform

### ISSUE THREAD

**Issue by jduss4** [OHS-Hosting-Infrastructure/complaint-tracker#90]
User Story:
As a developer
I want to manage services through code
So that we can document and automate our infrastructure.

Acceptance:
Given that I am a dev
When I push changes to the infrastructure code
Then I expect that they will be automatically deployed

This story has multiple tasks

**Comment by rahearn** [comment]
@jduss4 I _think_ this user story can get moved over to the "merged" column. What do you think?

**Comment by jduss4** [comment]
Yes!  I'm on it :D
