### ISSUE TITLE
View details about an activity report - M

### ISSUE THREAD

**Issue by rahearn** [OHS-Hosting-Infrastructure/complaint-tracker#97]
User Story:
As a program specialist
I want to view some detailed information about an activity report that's been linked to this complaint
So that I can have a fuller picture of the context of what's happened to address the complaint

Acceptance:
Given that I am a program specialist
When I view the complaint timeline
Then I can see some details as well as a link to open the full report in TTA Hub

**Comment by lauranash18f** [comment]
![Complaint Detail Page: Detail Header 1- Initial State](https://user-images.githubusercontent.com/85581840/132395013-27123fbb-0b24-48f7-96d6-5e17620d0af8.png)
![Complaint Detail Page: Detail Header 2- Add TTS Activity Report](https://user-images.githubusercontent.com/85581840/132395014-8719540a-855c-4d69-bca6-865b32ca572a.png)
![Complaint Detail Page: Detail Header 3- Two added](https://user-images.githubusercontent.com/85581840/132395015-9591f8f7-6ab4-4816-b4ba-7a037059095e.png)
![Complaint Detail Page: Detail Header 4- Add or edit multiple](https://user-images.githubusercontent.com/85581840/132395016-0278c073-0c8d-4b75-ba85-ca6c08017e6f.png)
![Complaint Detail Page: Detail Header 5- Stacked Edits](https://user-images.githubusercontent.com/85581840/132395017-d553ad5c-0d8a-4878-aeec-66e1b1c3f2cd.png)
![Complaint Detail Page: Detail Header 6- Add or edit multiple](https://user-images.githubusercontent.com/85581840/132395018-e6516018-269f-46a3-8771-85f0d3834d14.png)

**Comment by rahearn** [comment]
Double check figma for fields
